# Generated by Django 2.1.1 on 2019-01-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcasestep',
            name='webcasename',
        ),
    ]
