# Generated by Django 2.1.1 on 2019-01-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='Webcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Webcase.webcasename+', to='webtest.Webcase'),
        ),
    ]
