# Generated by Django 2.1.1 on 2019-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_remove_webcasestep_webcasename'),
    ]

    operations = [
        migrations.CreateModel(
            name='webtest_task',
            fields=[
                ('task_id', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('task_modelname', models.CharField(max_length=100, verbose_name='模块名称')),
                ('task_casename', models.CharField(max_length=200, verbose_name='任务用例名称')),
                ('task_status', models.CharField(default=True, max_length=200, verbose_name='状态')),
                ('task_retry', models.CharField(max_length=10, verbose_name='失败重跑次数')),
                ('task_result', models.CharField(max_length=20, verbose_name='测试结果')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
