# Generated by Django 2.1.1 on 2019-01-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_webtest_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtest_task',
            name='task_stepdesc',
            field=models.CharField(max_length=100, null=True, verbose_name='任务步骤描述'),
        ),
    ]
