# Generated by Django 2.1.1 on 2019-01-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0004_webtest_task_task_stepdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtest_task',
            name='case_id',
            field=models.CharField(max_length=200, null=True, verbose_name='上一级的ID'),
        ),
    ]
