# Generated by Django 2.1.1 on 2019-01-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_webtest_task_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcasestep',
            name='webkwargesfour',
            field=models.CharField(blank=True, max_length=200, verbose_name='参数4'),
        ),
        migrations.AlterField(
            model_name='webtest_task',
            name='case_id',
            field=models.CharField(max_length=200, null=True, verbose_name='测试用例名称的ID'),
        ),
    ]
