# Generated by Django 2.1.5 on 2019-01-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_auto_20190109_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receivers', models.CharField(max_length=100)),
                ('host_dir', models.CharField(max_length=20)),
                ('email_port', models.CharField(default='', max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('Headerfrom', models.CharField(max_length=20)),
                ('Headerto', models.CharField(max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
