# Generated by Django 2.1.5 on 2019-01-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0006_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='Headerfrom',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='email',
            name='Headerto',
        ),
        migrations.RemoveField(
            model_name='email',
            name='host_dir',
        ),
    ]
