# Generated by Django 2.1.1 on 2018-12-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0006_auto_20181221_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcasestep',
            name='webtestlocation',
            field=models.CharField(choices=[('id', 'id'), ('xpath', 'xpath'), ('css', 'css'), ('图片', '图片'), ('name', 'name'), ('link', 'link'), ('classname', 'classname'), ('tagname', 'tagname')], default='0', max_length=200, verbose_name='定位方式'),
        ),
    ]
