# Generated by Django 2.1.1 on 2018-10-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need_data_apis',
            name='Apirealresult',
        ),
    ]
