# Generated by Django 2.1.1 on 2018-10-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need_data_apis',
            old_name='Apiurl',
            new_name='Apiurl_data',
        ),
    ]
