# Generated by Django 2.1.1 on 2018-10-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singel_apis_task',
            name='task_Apischarger',
        ),
    ]
