# Generated by Django 2.1.1 on 2018-11-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_apis_task',
            name='task_log',
        ),
        migrations.RemoveField(
            model_name='singel_apis_task',
            name='task_log',
        ),
        migrations.AddField(
            model_name='process_apis_task',
            name='task_response',
            field=models.CharField(default='abc', max_length=500, verbose_name='返回结果'),
        ),
        migrations.AddField(
            model_name='singel_apis_task',
            name='task_response',
            field=models.CharField(default='abc', max_length=500, verbose_name='返回结果'),
        ),
    ]
