# Generated by Django 2.1.1 on 2018-10-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='need_data_apis',
            name='Apiparameter',
            field=models.CharField(max_length=800, null=True, verbose_name='请求信息'),
        ),
        migrations.AlterField(
            model_name='need_data_apis',
            name='Apiformdata',
            field=models.CharField(max_length=800, verbose_name='表单参数'),
        ),
        migrations.AlterField(
            model_name='need_data_apis',
            name='Apiheader',
            field=models.CharField(max_length=800, verbose_name='请求头参数'),
        ),
        migrations.AlterField(
            model_name='need_data_apis',
            name='Apimethod',
            field=models.CharField(default='GET', max_length=20, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='need_data_apis',
            name='depend_Apiname',
            field=models.CharField(max_length=100, verbose_name='用例名称'),
        ),
        migrations.AlterField(
            model_name='need_data_apis',
            name='productname',
            field=models.CharField(max_length=100, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='singel_apis',
            name='Apiformdata',
            field=models.CharField(max_length=800, verbose_name='表单参数'),
        ),
        migrations.AlterField(
            model_name='singel_apis',
            name='Apiheader',
            field=models.CharField(max_length=800, null=True, verbose_name='请求头参数'),
        ),
        migrations.AlterField(
            model_name='singel_apis',
            name='Apimethod',
            field=models.CharField(default='GET', max_length=20, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='singel_apis',
            name='Apiparameter',
            field=models.CharField(max_length=800, null=True, verbose_name='请求信息'),
        ),
    ]
