# Generated by Django 2.1.1 on 2018-09-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_product',
            name='modelname',
            field=models.CharField(default='', max_length=10, verbose_name='模块名'),
        ),
        migrations.AlterField(
            model_name='create_product',
            name='productid',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
