# Generated by Django 2.1.1 on 2018-10-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_remove_singel_apis_task_task_apischarger'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_apis_task',
            fields=[
                ('task_id', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('task_process_name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('task_modelname', models.CharField(max_length=100, verbose_name='模块名称')),
                ('task_depend_Apiname', models.CharField(max_length=100, verbose_name='用例名称')),
                ('task_Apiurl_data', models.CharField(max_length=200, verbose_name='接口地址')),
                ('task_Apimethod', models.CharField(default='GET', max_length=20, verbose_name='请求方式')),
                ('task_Apiheader', models.CharField(max_length=800, verbose_name='请求头参数')),
                ('task_Apiparameter', models.CharField(max_length=800, null=True, verbose_name='请求信息')),
                ('task_Apiformdata', models.CharField(max_length=800, verbose_name='表单参数')),
                ('task_Apidependdata', models.CharField(max_length=100, verbose_name='依赖的数据')),
                ('task_Apiexpectresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('task_status', models.CharField(default=True, max_length=200, verbose_name='状态')),
                ('task_log', models.CharField(max_length=500, verbose_name='日志')),
                ('task_retry', models.CharField(max_length=10, verbose_name='失败重跑次数')),
            ],
        ),
    ]
