# Generated by Django 2.1.1 on 2018-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_remove_need_data_apis_apirealresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='singel_apis_task',
            fields=[
                ('task_id', models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('task_modelname', models.CharField(max_length=200, verbose_name='任务模块')),
                ('task_casename', models.CharField(max_length=200, verbose_name='任务用例名称')),
                ('task_status', models.CharField(max_length=200, verbose_name='状态')),
                ('task_log', models.CharField(max_length=500, verbose_name='日志')),
                ('task_retry', models.CharField(max_length=10, verbose_name='失败重跑次数')),
            ],
        ),
    ]
