# Generated by Django 2.1.1 on 2018-10-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_process_apis_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_apis_task',
            name='task_result',
            field=models.CharField(default='abc', max_length=20, verbose_name='测试结果'),
        ),
        migrations.AddField(
            model_name='singel_apis_task',
            name='task_result',
            field=models.CharField(default='abc', max_length=20, verbose_name='测试结果'),
        ),
    ]
