# Generated by Django 2.1.1 on 2018-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_singel_apis_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_status',
            field=models.CharField(default=True, max_length=200, verbose_name='状态'),
        ),
    ]
