# Generated by Django 2.1.1 on 2018-10-10 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20180914_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='need_data_Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apiname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('Apiurl', models.CharField(max_length=200, verbose_name='接口地址')),
                ('Apiheader', models.CharField(max_length=800, verbose_name='请求头信息')),
                ('Apiformdata', models.CharField(max_length=800, verbose_name='请求参数')),
                ('Apimethod', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'path')], default='get', max_length=200, null=True, verbose_name='请求方法')),
                ('Apiexpectresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('Apirealresult', models.CharField(max_length=200, verbose_name='实际返回结果')),
                ('Apistatus', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('Apitest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Apitest')),
            ],
        ),
        migrations.CreateModel(
            name='singel_Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apiname', models.CharField(max_length=100, verbose_name='接口名称')),
                ('Apiurl', models.CharField(max_length=200, verbose_name='Url地址')),
                ('Apiheader', models.CharField(max_length=800, null=True, verbose_name='请求头信息')),
                ('Apiparameter', models.CharField(max_length=800, null=True, verbose_name='请求头信息')),
                ('Apiformdata', models.CharField(max_length=800, verbose_name='请求参数')),
                ('Apimethod', models.CharField(choices=[('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch')], default='0', max_length=200, verbose_name='请求方法')),
                ('Apiexpectresult', models.CharField(max_length=200, verbose_name='预期结果')),
                ('Apirealresult', models.CharField(max_length=200, verbose_name='实际结果')),
                ('Apischarger', models.CharField(max_length=50, verbose_name='负责人')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='apis',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='apistep',
            name='Apitest',
        ),
        migrations.AlterField(
            model_name='create_product',
            name='productid',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Apis',
        ),
        migrations.DeleteModel(
            name='Apistep',
        ),
        migrations.AddField(
            model_name='singel_apis',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Create_product'),
        ),
    ]
