# Generated by Django 2.1.1 on 2018-10-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20181030_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_apis_task',
            name='task_result',
            field=models.CharField(max_length=20, verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_result',
            field=models.CharField(max_length=20, verbose_name='测试结果'),
        ),
    ]
