# Generated by Django 2.1.1 on 2018-11-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20181030_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_apis_task',
            name='task_Apiurl_data',
            field=models.CharField(max_length=1024, verbose_name='接口地址'),
        ),
        migrations.AlterField(
            model_name='process_apis_task',
            name='task_status',
            field=models.BooleanField(default='未运行', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_status',
            field=models.BooleanField(default='未运行', max_length=200, verbose_name='状态'),
        ),
    ]
