# Generated by Django 2.1.1 on 2018-11-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20181101_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_apis_task',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process_apis_task',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='singel_apis_task',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='singel_apis_task',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='process_apis_task',
            name='task_status',
            field=models.CharField(default='未运行', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_status',
            field=models.CharField(default='未运行', max_length=200, verbose_name='状态'),
        ),
    ]
