# Generated by Django 2.1.1 on 2018-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20181101_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_apis_task',
            name='task_status',
            field=models.CharField(default='True', max_length=200, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='singel_apis_task',
            name='task_status',
            field=models.CharField(default='True', max_length=200, verbose_name='状态'),
        ),
    ]
