# Generated by Django 2.1.1 on 2018-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_steps',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
