# Generated by Django 2.1.1 on 2018-11-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step1',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step10',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step11',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step12',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step13',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step14',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step15',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step16',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step17',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step18',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step19',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step2',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step20',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step3',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step4',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step5',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step6',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step7',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step8',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='web_case_step9',
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='creat_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webassertdata',
            field=models.CharField(default=None, max_length=200, verbose_name='验证数据'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webcomments',
            field=models.CharField(default=None, max_length=200, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webelement',
            field=models.CharField(default=None, max_length=800, verbose_name='控件元素'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webfindmethod',
            field=models.CharField(default=None, max_length=200, verbose_name='定位方式'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webopelement',
            field=models.CharField(default=None, max_length=200, verbose_name='操作方法'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webtestdata',
            field=models.CharField(max_length=200, null=True, verbose_name='测试数据'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webtestresult',
            field=models.BooleanField(default=None, verbose_name='测试结果'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webteststep',
            field=models.CharField(default=None, max_length=200, verbose_name='测试步骤'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webteststepdesc',
            field=models.CharField(default=None, max_length=200, verbose_name='测试对象描述'),
        ),
        migrations.AlterField(
            model_name='add_web_testcase',
            name='web_case_name',
            field=models.CharField(default=None, max_length=50, verbose_name='web测试名称'),
        ),
    ]
