# Generated by Django 2.1.1 on 2018-12-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_web_name',
            new_name='Webcase',
        ),
        migrations.RenameModel(
            old_name='edit_case_step',
            new_name='Webcasestep',
        ),
    ]
