# Generated by Django 2.1.1 on 2018-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_case_step',
            name='webcase',
            field=models.CharField(max_length=200, verbose_name='测试模块'),
        ),
    ]
