# Generated by Django 2.1.1 on 2018-12-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit_case_step',
            options={'verbose_name': 'web测试步骤', 'verbose_name_plural': 'web测试步骤'},
        ),
        migrations.RemoveField(
            model_name='edit_case_step',
            name='img',
        ),
    ]
