# Generated by Django 2.1.1 on 2018-12-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0002_auto_20181219_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_web_name',
            options={'verbose_name': 'web测试步骤', 'verbose_name_plural': 'web测试步骤'},
        ),
        migrations.AlterModelOptions(
            name='edit_case_step',
            options={},
        ),
    ]
