# Generated by Django 2.1.1 on 2018-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0002_auto_20181120_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_steps',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
