# Generated by Django 2.1.1 on 2018-11-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0002_auto_20181120_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_steps',
            name='webcase_models',
            field=models.CharField(max_length=250, verbose_name='所属模块'),
        ),
    ]
