# Generated by Django 2.1.1 on 2018-11-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0003_auto_20181114_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='creat_time',
        ),
    ]
