# Generated by Django 2.1.1 on 2018-11-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0003_remove_edit_case_step_webcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_web_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcase_models', models.CharField(max_length=250, verbose_name='所属模块')),
                ('webcasename', models.CharField(max_length=50, verbose_name='测试用例名称')),
                ('webcasedesc', models.CharField(max_length=50, verbose_name='步骤描述')),
                ('webteststep', models.CharField(max_length=200, verbose_name='测试步骤')),
                ('webcase_charger', models.CharField(max_length=200, verbose_name='负责人')),
                ('creat_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
        migrations.DeleteModel(
            name='add_web_steps',
        ),
        migrations.RemoveField(
            model_name='edit_case_step',
            name='webcasename',
        ),
        migrations.AddField(
            model_name='edit_case_step',
            name='webtest_step',
            field=models.CharField(max_length=200, null=True, verbose_name='测试步骤'),
        ),
        migrations.AddField(
            model_name='edit_case_step',
            name='Webcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_robotframework.add_web_name'),
        ),
    ]
