# Generated by Django 2.1.1 on 2018-11-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0004_remove_add_web_testcase_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_web_testcase',
            name='webcase_models',
            field=models.CharField(default=None, max_length=50, verbose_name='所属模块'),
        ),
    ]
