# Generated by Django 2.1.1 on 2018-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0006_add_web_testcase_webcase_charger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_testcase',
            name='webcase_charger',
            field=models.CharField(max_length=200, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='add_web_testcase',
            name='webcase_models',
            field=models.CharField(max_length=50, verbose_name='所属模块'),
        ),
    ]
