# Generated by Django 2.1.1 on 2018-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0007_auto_20181115_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_web_testcase',
            name='creat_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
