# Generated by Django 2.1.1 on 2018-11-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0008_auto_20181122_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_case_step',
            name='Webcase',
        ),
    ]
