# Generated by Django 2.1.1 on 2018-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0008_add_web_testcase_creat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='webelement',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='webopelement',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='webtestdata',
        ),
        migrations.RemoveField(
            model_name='add_web_testcase',
            name='webteststepdesc',
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webkwargesone',
            field=models.CharField(default=None, max_length=200, verbose_name='参数1'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webkwargesthree',
            field=models.CharField(default=None, max_length=200, verbose_name='参数3'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webkwargestwo',
            field=models.CharField(default=None, max_length=200, verbose_name='参数2'),
        ),
        migrations.AddField(
            model_name='add_web_testcase',
            name='webtestlocation',
            field=models.CharField(default=None, max_length=200, verbose_name='定位路径'),
        ),
        migrations.AlterField(
            model_name='add_web_testcase',
            name='webfindmethod',
            field=models.CharField(default=None, max_length=200, verbose_name='方法|操作'),
        ),
    ]
