# Generated by Django 2.1.1 on 2018-11-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0010_auto_20181115_1702'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_web_testcase',
            new_name='add_web_steps',
        ),
    ]
