# Generated by Django 2.1.1 on 2018-11-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0011_auto_20181116_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_web_steps',
            name='webcasedesc',
            field=models.CharField(default=None, max_length=50, verbose_name='步骤描述'),
            preserve_default=False,
        ),
    ]
