# Generated by Django 2.1.1 on 2018-11-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0011_auto_20181123_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_case_step',
            name='img',
            field=models.ImageField(default='abc', upload_to='img'),
        ),
    ]
