# Generated by Django 2.1.1 on 2018-11-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0012_edit_case_step_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_case_step',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
