# Generated by Django 2.1.1 on 2018-11-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0012_add_web_steps_webcasedesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_steps',
            name='webtestresult',
            field=models.BooleanField(default=None, verbose_name='测试结果'),
        ),
    ]
