# Generated by Django 2.1.1 on 2018-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0014_auto_20181116_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_web_steps',
            name='webtestresult',
            field=models.CharField(max_length=50, verbose_name='测试结果'),
        ),
    ]
