# Generated by Django 2.1.1 on 2018-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0015_auto_20181116_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit_case_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtestlocation', models.CharField(max_length=200, verbose_name='定位路径')),
                ('webfindmethod', models.CharField(max_length=200, verbose_name='方法|操作')),
                ('webkwargesone', models.CharField(max_length=200, verbose_name='参数1')),
                ('webkwargestwo', models.CharField(max_length=200, verbose_name='参数2')),
                ('webkwargesthree', models.CharField(max_length=200, verbose_name='参数3')),
                ('webassertdata', models.CharField(max_length=200, verbose_name='验证数据')),
                ('webtestresult', models.CharField(max_length=50, verbose_name='测试结果')),
                ('webcomments', models.CharField(max_length=200, verbose_name='备注')),
            ],
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webassertdata',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webcomments',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webfindmethod',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webkwargesone',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webkwargesthree',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webkwargestwo',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webtestlocation',
        ),
        migrations.RemoveField(
            model_name='add_web_steps',
            name='webtestresult',
        ),
    ]
