# Generated by Django 2.1.1 on 2018-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0016_auto_20181119_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_case_step',
            name='web_case_id',
            field=models.CharField(default=2, max_length=500, verbose_name='用例ID'),
            preserve_default=False,
        ),
    ]
