# Generated by Django 2.1.1 on 2018-11-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0019_auto_20181119_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_case_step',
            name='web_case_id',
        ),
        migrations.AddField(
            model_name='edit_case_step',
            name='webcase',
            field=models.ForeignKey(default='abc', on_delete=django.db.models.deletion.CASCADE, to='web_robotframework.add_web_steps'),
        ),
        migrations.AddField(
            model_name='edit_case_step',
            name='webcasename',
            field=models.CharField(default='abc', max_length=200, verbose_name='测试标题'),
        ),
    ]
