# Generated by Django 2.1.1 on 2018-11-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_robotframework', '0021_auto_20181120_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_web_steps',
            name='web_case_id',
        ),
        migrations.AddField(
            model_name='add_web_steps',
            name='id',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
