# Generated by Django 2.1.5 on 2019-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singel_apis',
            name='Apistatuscode',
            field=models.CharField(max_length=200, verbose_name='状态码'),
        ),
    ]
